# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - name: "Release R github"
    r: release
    env: bdverse='github'
    after_success:
      - Rscript -e 'covr::codecov()'
    r_github_packages:
      - bd-R/bdDwC
      - bd-R/bdchecks
      - bd-R/bdutilities
      - bd-R/bdutilities.app
    
  - name: "Release R github OSX"
    r: release
    env: bdverse='github'
    r_github_packages:
      - bd-R/bdDwC
      - bd-R/bdchecks
      - bd-R/bdutilities
      - bd-R/bdutilities.app
    os: osx
  - r: devel
  - r: oldrel
  - r: 3.6

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - libv8-dev
