# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_check_args: "--as-cran"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - libv8-dev