app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("module-02-configure-cleaning-test")

app$uploadFile(`bdFileInput-inputFile` = "puma_concolor.csv")
app$setInputs(dataToConfigure = "click")
Sys.sleep(5)
app$snapshot()
app$setInputs(taxonMain = TRUE)
app$setInputs(spatialMain = TRUE)
app$setInputs(precisionCoord = TRUE)
app$setInputs(countryCoord = TRUE)
app$setInputs(elevationCoord = TRUE)
app$setInputs(temporalMain = TRUE)
app$setInputs(smallerDates = TRUE)
app$setInputs(smallerIssues = TRUE)
app$setInputs(taxonLevel = "Class")
app$setInputs(spatialResolution = 1000)
app$setInputs(temporalEarliest = c("2000-01-01", "2019-09-29"))
app$setInputs(temporalEarliest = c("2000-01-01", "2019-01-01"))
app$snapshot()
app$setInputs(questionnaireTab = "option2")
app$snapshot()
app$setInputs(DC_basisOfRecordBadlyFormed = TRUE)
app$setInputs(DC_classUnknown = TRUE)
app$setInputs(DC_coordinatePrecisionMismatch = TRUE)
app$setInputs(DC_coordinatesZero = TRUE)
app$setInputs(DC_countryMismatch = TRUE)
app$setInputs(DC_countryNameUnknown = TRUE)
app$setInputs(DC_dataGeneralised = TRUE)
app$setInputs(DC_dateIdentifiedInFuture = TRUE)
app$setInputs(DC_dateNull = TRUE)
app$setInputs(DC_dayInvalid = TRUE)
app$setInputs(DC_depthOutOfRange = TRUE)
app$setInputs(DC_elevationOutOfRange = TRUE)
app$setInputs(DC_eventDateInFuture = TRUE)
app$setInputs(DC_identifiedDateImprobable = TRUE)
app$setInputs(DC_individualCountInvalid = TRUE)
app$setInputs(DC_modifiedInFuture = TRUE)
app$setInputs(DC_monthInvalid = TRUE)
app$setInputs(DC_namePublishedYearInFuture = TRUE)
app$setInputs(DC_occurrenceIdNotGuid = TRUE)
app$setInputs(DC_precisionRangeMismatch = TRUE)
app$setInputs(DC_uncertaintyRangeMismatch = TRUE)
app$setInputs(DC_yearMissing = TRUE)
app$snapshot()
