app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("module-02-configure-cleaning-test")

app$uploadFile(`bdFileInput-inputFile` = "puma_concolor.csv")
app$setInputs(dataToConfigure = "click")
Sys.sleep(5)
app$snapshot()
app$setInputs(taxonMain = TRUE)
app$setInputs(taxonLevel = "Class")
app$setInputs(spatialMain = TRUE)
app$setInputs(spatialResolution = 1000)
app$setInputs(precisionCoord = TRUE)
app$setInputs(countryCoord = TRUE)
app$setInputs(temporalMain = TRUE)
app$setInputs(temporalEarliest = c("2000-01-01", "2019-12-25"))
app$setInputs(smallerDates = TRUE)
app$setInputs(smallerIssues = TRUE)
app$snapshot()
app$setInputs(spatialResolution_ctrl = FALSE)
app$snapshot()
app$setInputs(questionnaireTab = "option2")
Sys.sleep(5)
app$snapshot()
app$setInputs(DC_notification_datageneralizations_notempty = TRUE)
app$setInputs(typeInput = "DC_notification_datageneralizations_notempty")
app$setInputs(DC_notification_establishmentmeans_notempty = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty"))
app$setInputs(DC_validation_basisofrecord_empty = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty", "DC_validation_basisofrecord_empty"))
app$setInputs(DC_validation_dateidentified_notstandard = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty", "DC_validation_basisofrecord_empty", "DC_validation_dateidentified_notstandard"))
app$setInputs(DC_validation_family_notfound = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty", "DC_validation_basisofrecord_empty", "DC_validation_dateidentified_notstandard", "DC_validation_family_notfound"))
app$setInputs(DC_validation_occurrencestatus_empty = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty", "DC_validation_basisofrecord_empty", "DC_validation_dateidentified_notstandard", "DC_validation_family_notfound", "DC_validation_occurrencestatus_empty"))
app$setInputs(DC_validation_year_outofrange = TRUE)
app$setInputs(typeInput = c("DC_notification_datageneralizations_notempty", "DC_notification_establishmentmeans_notempty", "DC_validation_basisofrecord_empty", "DC_validation_dateidentified_notstandard", "DC_validation_family_notfound", "DC_validation_occurrencestatus_empty", "DC_validation_year_outofrange"))
app$snapshot()
