# This work flow only works when a repository_dispatch event with custom type "bdverse-level-CI-trigger" happens.
#It must be in Master branch.

name:  Level 1 CI
on:
  repository_dispatch:
    types: [bdverse-level-CI-trigger]
jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
