name: Level 0 CI
# this CI runs when a new push or Pull Request comes to Master branch. At the end of the run,it sends "repository_dispatch" message to other repositories mentioned in
# repo matrix. 
# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ new_bdclean ]
  pull_request:
    branches: [ new_bdclean ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
# below lines will run after R-CMD-check is OK
# this sends trigger to repos mentioned below.
# workflow to be triggered has to be in master branch.
# currently REPO_ACCESS_TOKEN is in organization secret with only public repo access.
  dispatch:
    needs: R-CMD-check
    strategy:
      matrix:
        repo: ['bd-R/bdutilities', 'bd-R/bdDwC', 'bd-R/bdchecks', 'bd-R/bdverse', 'bd-R/bdutilities.app' ,'bd-R/bdDwC.app', 'bd-R/bdchecks.app']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: bdverse-level-CI-trigger
